# Reconstruct configuration file that reads from a USRP and sends things over UDP

# Frequencies set up to monitor all ACARS frequencies (in megahertz):
# 129.125
# 129.350
# 129.525
# 130.025
# 130.450
# 130.825
# 131.125
# 131.425
# 131.550
# 131.725 (10)
# 131.850
# 136.575
# 136.650
# 136.675
# 136.700
# 136.725
# 136.750
# 136.775
# 136.800
# 136.850
# 136.975
#
# To achieve that:
# Center on 135 MHz
# Mask bins 0..901 (85-129 MHz)
# Mask bins 1068..2048 (137-185 MHz)

[source]
type = "n210"
frequency = 131e6
gain = 31.5
antenna = "TX/RX"
args = { addr = "192.168.10.2" }

[[source.compression.thresholds]]
bins = { start = 0, end = 2048 }
# This was previously 75000
threshold = 75000

# Mask out lower frequencies: 81 to 125 MHz
[[source.compression.masks]]
start = 0
end = 901

# Mask out higher frequencies: 138 to 181
[[source.compression.masks]]
start = 1170
end = 2048

[ui]
log_level = "Debug"

# The bands to reconstruct
# Each band uses 2 bins -> sample rate 97.65625 kHz

# 129.125 MHz
[[bands]]
bins = 2
frequency = -1875000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/129.125.pipe"}

# 129.350 MHz
[[bands]]
bins = 2
frequency = -1650000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/129.350.pipe"}

# 129.525 MHz
[[bands]]
bins = 2
frequency = -1475000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/129.525.pipe"}

# 130.025 MHz
[[bands]]
bins = 2
frequency = -975000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/130.025.pipe"}

# 130.450 MHz
[[bands]]
bins = 2
frequency = -550000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/130.450.pipe"}

# 130.825 MHz
[[bands]]
bins = 2
frequency = -175000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/130.825.pipe"}

# 131.125 MHz
[[bands]]
bins = 2
frequency = 125000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/131.125.pipe"}

# 131.425 MHz
[[bands]]
bins = 2
frequency = 425000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/131.425.pipe"}

# 131.550 MHz
[[bands]]
bins = 2
frequency = 550000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/131.550.pipe"}

# 131.725 MHz
[[bands]]
bins = 2
frequency = 725000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/131.725.pipe"}

# 131.850 MHz
[[bands]]
bins = 2
frequency = 850000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/131.850.pipe"}

# 136.575 MHz
[[bands]]
bins = 2
frequency = 5575000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/136.575.pipe"}

# 136.650 MHz
[[bands]]
bins = 2
frequency = 5650000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/136.650.pipe"}

# 136.675 MHz
[[bands]]
bins = 2
frequency = 5675000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/136.675.pipe"}

# 136.700 MHz
[[bands]]
bins = 2
frequency = 5700000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/136.700.pipe"}

# 136.725 MHz
[[bands]]
bins = 2
frequency = 5725000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/136.725.pipe"}

# 136.750 MHz
[[bands]]
bins = 2
frequency = 5750000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/136.750.pipe"}

# 136.775 MHz
[[bands]]
bins = 2
frequency = 5775000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/136.775.pipe"}

# 136.800 MHz
[[bands]]
bins = 2
frequency = 5800000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/136.800.pipe"}

# 136.850 MHz
[[bands]]
bins = 2
frequency = 5850000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/136.850.pipe"}

# 136.975 MHz
[[bands]]
bins = 2
frequency = 5975000.0
destination = { type = "file", path = "/home/samcrow/Documents/CurrentClasses/Research/Compression/acars_testing/multi_realtime/pre_resample_pipes/136.975.pipe"}
