# Reconstruct configuration file that reads from a USRP and sends things over UDP

# Frequencies set up to monitor all ACARS frequencies (in megahertz):
# 129.125
# 129.350
# 129.525
# 130.025
# 130.450
# 130.825
# 131.125
# 131.425
# 131.550
# 131.725
# 131.850
# 136.575
# 136.650
# 136.675
# 136.700
# 136.725
# 136.750
# 136.775
# 136.800
# 136.850
# 136.975
#
# To achieve that:
# Center on 135 MHz
# Mask bins 0..901 (85-129 MHz)
# Mask bins 1068..2048 (137-185 MHz)

[source]
type = "n210"
frequency = 131e6
gain = 31.5
antenna = "TX/RX"
args = { addr = "192.168.10.2" }

# Set lower thresholds for testing
[[source.compression.thresholds]]
bins = { start = 0, end = 2048 }
threshold = 2100

[[source.compression.masks]]
start = 0
end = 901

[[source.compression.masks]]
start = 1068
end = 2048

[ui]
log_level = "Debug"

# 131.550, 97.656 25 kHz
[[bands]]
bins = 2
frequency = 0.550e6

[bands.destination]
type = "udp"
remote_address = "127.0.0.1:9930"
