# Reconstruct configuration file that reads from a USRP and sends things over UDP

# Frequencies set up to monitor all ACARS frequencies (in megahertz):
# 129.125
# 129.350
# 129.525
# 130.025
# 130.450
# 130.825
# 131.125
# 131.425
# 131.550
# 131.725
# 131.850
# 136.575
# 136.650
# 136.675
# 136.700
# 136.725
# 136.750
# 136.775
# 136.800
# 136.850
# 136.975
#
# To achieve that:
# Center on 135 MHz
# Mask bins 0..901 (85-129 MHz)
# Mask bins 1068..2048 (137-185 MHz)

[source]
type = "n210"
frequency = 131e6
gain = 31.5
antenna = "TX/RX"
args = { addr = "192.168.10.2" }

# Set lower thresholds for testing
[[source.compression.thresholds]]
bins = { start = 0, end = 2048 }
threshold = 2100

[[source.compression.masks]]
start = 0
end = 901

[[source.compression.masks]]
start = 1068
end = 2048

[ui]
log_level = "Debug"

# The bands to reconstruct
# Each band uses 2 bins -> sample rate 97.65625 kHz

# 129.125 MHz
[[bands]]
bins = 2
frequency = -1875000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 129.350 MHz
[[bands]]
bins = 2
frequency = -1650000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 129.525 MHz
[[bands]]
bins = 2
frequency = -1475000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 130.025 MHz
[[bands]]
bins = 2
frequency = -975000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 130.450 MHz
[[bands]]
bins = 2
frequency = -550000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 130.825 MHz
[[bands]]
bins = 2
frequency = -175000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 131.125 MHz
[[bands]]
bins = 2
frequency = 125000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 131.425 MHz
[[bands]]
bins = 2
frequency = 425000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 131.550 MHz
[[bands]]
bins = 2
frequency = 550000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 131.725 MHz
[[bands]]
bins = 2
frequency = 725000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 131.850 MHz
[[bands]]
bins = 2
frequency = 850000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 136.575 MHz
[[bands]]
bins = 2
frequency = 5575000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 136.650 MHz
[[bands]]
bins = 2
frequency = 5650000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 136.675 MHz
[[bands]]
bins = 2
frequency = 5675000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 136.700 MHz
[[bands]]
bins = 2
frequency = 5700000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 136.725 MHz
[[bands]]
bins = 2
frequency = 5725000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 136.750 MHz
[[bands]]
bins = 2
frequency = 5750000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 136.775 MHz
[[bands]]
bins = 2
frequency = 5775000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 136.800 MHz
[[bands]]
bins = 2
frequency = 5800000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 136.850 MHz
[[bands]]
bins = 2
frequency = 5850000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}

# 136.975 MHz
[[bands]]
bins = 2
frequency = 5975000.0
destination = { type = "tcp_client", server_address = "127.0.0.1:9930"}
